[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs
board_build.partitions = partitions.csv
upload_protocol = esptool

lib_deps =
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    bblanchon/ArduinoJson
    tzapu/WiFiManager
